site_name: SEDOS Project

nav:
    - Welcome: index.md
    - 'Reference Energy System':
        - 'Overview': 'visitor/structure/overview.md'
        - 'Model Base': 'visitor/structure/model_frame.md'
        - 'Exogenous Values': 'visitor/structure/exogenous_values.md'
        - 'Model Structure': ''
        - 'Aggregations': ''
    - 'Reference Dataset':
        - 'Overview': 'visitor/data/overview.md'
        - 'Data': 'visitor/data/input_data.md'
        - 'Metadata': 'visitor/data/metadata.md'
        - 'Ontology': 'visitor/data/ontology.md'
        - 'Licensing': 'visitor/data/licensing.md'
        - 'Data Preface': 'developer/data_preface.md'
        - 'Nomenclature': 'visitor/nomenclature.md'
    - 'Model Application':
        - 'Scenarios': 'visitor/model/scenarios.md'
        - 'Results': 'visitor/model/results.md'
        - 'GUI': ''
    - SEDOS Developer:
        - '(Meta)data requirements':
            - 'Overview': 'developer/data_requirements/overview.md'
            - 'Data': 'developer/data_requirements/input_data.md'
            - 'Metadata': 'developer/data_requirements/metadata.md'
            - 'Ontology': 'developer/data_requirements/ontology.md'
            - 'Licensing': 'developer/data_requirements/licensing.md'
        - 'How to contribute data?': 'developer/how_to_contribute_data.md'
        - 'Data preface': 'developer/data_preface.md'
        - 'FAQ': 'developer/faq.md'
    - 'Glossary': 'glossary.md'

markdown_extensions:
    - toc:
        permalink: True
        separator: "#"
        toc_depth: 3
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.tabbed:
        alternate_style: true
    - def_list
    - pymdownx.tasklist:
        custom_checkbox: true

    - pymdownx.highlight:
        anchor_linenums: true
    - pymdownx.inlinehilite
    - pymdownx.snippets
    - admonition
    - pymdownx.arithmatex:
        generic: true
    - footnotes
    - pymdownx.details
    - pymdownx.superfences:
        custom_fences:
          - name: mermaid
            class: mermaid
            format: !!python/name:pymdownx.superfences.fence_code_format
    - pymdownx.mark
    - attr_list
    - pymdownx.emoji:
        emoji_index: !!python/name:material.extensions.emoji.twemoji
        emoji_generator: !!python/name:material.extensions.emoji.to_svg
    - pymdownx.tabbed:
        alternate_style: true

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - toc.integrate
  language: en
  palette:
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/eye
        name: Switch to dark mode
    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/eye-outline
        name: Switch to light mode

  icon:
    repo: fontawesome/brands/github
  logo: graphics/sedos.png
  favicon: graphics/sedos_favicon.png

extra_css:
  - stylesheets/extra.css


plugins:
  - search
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            show_root_heading: true
            show_source: false
            docstring_style: numpy
            docstring_section_style: spacy
  - include-markdown

repo_url: https://github.com/sedos-project/organization
site_description: The documentation of the SEDOS data management

copyright: |
  &copy; 2024 - SEDOS Project Team

# in case hyperlinks are wanted
#<a href="https://reiner-lemoine-institut.de/"  target="_blank" rel="noopener">RLI</a> and <a
#href="https://fortiss.org"  target="_blank" rel="noopener">fortiss GmbH</a>
