site_name: SEDOS Project
nav:
    - Home: 'index.md'
    - 'Data requirements':
       - 'How to contribute data?': 'data_requirements/overview.md'
       - 'Input/Output Data Conventions': 'data_requirements/input_data.md'
       - 'Metadata': 'data_requirements/metadata.md'
       - 'Ontology': 'data_requirements/data_annotation_ontology.md'
       - 'Licensing': 'data_requirements/licensing.md'
markdown_extensions:
    - toc:
        permalink: "#"