site_name: SEDOS Project
nav:
    - 'Data requirements':
       - 'Overview': 'data_requirements/overview.md'
       - 'Data': 'data_requirements/input_data.md'
       - 'Nomenclature': 'data_requirements/nomenclature.md'
       - 'Metadata': 'data_requirements/metadata.md'
       - 'Ontology': 'data_requirements/ontology.md'
       - 'Licensing': 'data_requirements/licensing.md'
    - 'How to contribute data?': 'how_to_contribute_data.md'
    - 'Data preface': 'data_preface.md'
    - 'FAQ': 'faq.md'
    - 'Glossary': 'glossary.md'
markdown_extensions:
    - toc:
        permalink: True
        separator: "#"
    - admonition
    - pymdownx.details
    - pymdownx.superfences
    - pymdownx.tabbed:
        alternate_style: true
    - def_list
    - pymdownx.tasklist:
        custom_checkbox: true
