name: MkDocs Build and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Install Dependencies
      run: pip install --upgrade -r requirements.txt

    - name: Build MkDocs
      run: mkdocs build

    - name: Archive MkDocs Build
      uses: actions/upload-artifact@v2
      with:
        name: mkdocs-artifacts
        path: ./built_docs_for_gh_pages  # Change this to your MkDocs build directory
